project_name          = "how-accurate-is-hk-observatory"
region                = "asia-east2"
forecast_bucket_name  = "hko-forecast"
fnd_bucket_name       = "hko-fnd"
gcf_bucket_name       = "hko-gcf"
rhrread_bucket_name   = "hko-rhrread"