project_name            = "how-accurate-is-hk-observatory"
region                  = "asia-east2"
forecast_bucket_name    = "hko-forecast"
fnd_bucket_name         = "hko-fnd"
gcf_bucket_name         = "hko-gcf"
rainfall_bucket_name    = "hko-rainfall"
rhrread_bucket_name     = "hko-rhrread"
temperature_bucket_name = "hko-temperature"